// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 26.02.2026, 20:25:48
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["/home/project/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/project/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/project/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/project/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/project/plugins/**/*.{js,ts,mjs}","/home/project/composables/**/*.{js,ts,mjs}","/home/project/utils/**/*.{js,ts,mjs}","/home/project/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/project/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/project/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/project/app.config.{js,ts,mjs}","/home/project/app/spa-loading-template.html"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;